AWSTemplateFormatVersion: '2010-09-09'
Description: 'Test template'

Parameters:
  ProjectName:
    Type: String
    Default: 'test'

Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

Outputs:
  VPCId:
    Value: !Ref TestVPC
